#JWT configuration
jwt:
  secret: blissno1
  expiration: 3600000


spring:
  application:
    name: auth
  datasource:
      url: jdbc:postgresql://localhost:5432/user-server
      username: postgres
      password: 123456
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

server:
  port: 8083